name: "infra preview & deploy"

on:
  push:
    branches:
      - master
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.2.8
  TF_PROJECT: tastylog
  TF_ENVIRONMENT: dev

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    outputs:
      IF_PLAN_EXITCODE: ${{steps.plan.outputs.exitcode}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TF_VERSION}}
      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ROLE_ARN}}
      - name: Terraform init
        id: plan
        run: |
          terraform init -no-color
      - name: Terraform validate
        run: |
          terraform validate -no-color
      - name: Terraform plan
        continue-on-error: true
        run: |
          terraform plan \
            -var 'project=${{env.TF_PROJECT}}' \
            -var 'environment=${{env.TF_ENVIRONMENT}}' \
            -var 'username=${{secrets.MYSQL_USERNAME}}' \
            -var 'password=${{secrets.MYSQL_PASSWORD}}' \
            -input=false \
            -no-color \
            -detailed-exitcode
      - name: Slack notify
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C02U16MMDAS"
          payload: |
            {
             "attachments": [
               {
                 "blocks": [
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
                       "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                     }
                   },
                   {
                     "type": "header",
                     "text": {
                       "type": "plain_text",
                       "text": "This is a header block ${{github.server_url}}/${{github.repository}} /actions/runs/${{github.run_id}}",
                       "emoji": true
                     }
                   }
                 ]
               }
             ]
            }
