name: "slack notify"

on:
  workflow_dispatch:

jobs:
  notify:
    name: Slack notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C02U16MMDAS"
          payload: |
            {
             "attachments": [
               {
                 "blocks": [
                   {
                     "type": "section",
                     "text": {
                       "type": "mrkdwn",
                       "text": "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link>"
                     }
                   },
                   {
                     "type": "header",
                     "text": {
                       "type": "plain_text",
                       "text": "This is a header block",
                       "emoji": true
                     }
                   }
                 ]
               }
             ]
            }
